<?php namespace DiafIP {

    /**
     * Diese Datei nicht bearbeiten - Do not edit this File
     * Bearbeiten sie für Ihre lokalen Einstellungen
     * die Datei config.local.php
     */

    /**
     * @author    Knut Wetzig <knwetzig@gmail.com>
     * @copyright 2012-2014 Deutsches Institut für Animationsfilm
     * @version   $Id$
     * @package   DiafIP\configs
     */

    require_once "service.php";
    require_once "Auth.php";
    require_once "MDB2.php";
    require_once "Smarty.class.php";
    require_once "entity.interface.php";
    require_once "pname.interface.php";
    require_once "person.interface.php";
    require_once "fibimain.interface.php";
    require_once "figd2.interface.php";
    require_once "bibl2.interface.php";

    const
        /**
         * Regex für Namen - Keine Interpunktion, nur runde Klammern
         */
    REG_NAMEN  = '^[^`*+!-\':-@[-^{-~]+$',
    REG_ANZAHL = '([1-9]+[\d]*){1,1}',
        // Dezimalzahl -1,2e-3
    REG_DZAHL  = '^[-+]?[\d]*[.,]?[\d]+([eE][-+]?[\d]+)?',
    REG_PLZ    = '^[\d]{4,7}$',
    REG_DAUER  = '^(([\d]+[hH])?([\d]+[mM])?([\d]*(([.][\d]+)?|[sS]))?|([\d]+[:][\d]+[:][\d]+)+([.][\d]+)?)$',
    REG_BOOL   = '(^(true|[1]|false|[0])\b){1,1}',
    REG_TELNR = '^[+\d][\d\s]*$', // +49 351 123456
    REG_EMAIL = '[\w].*[@].*[.][\w]{2,3}', //xxx@yyy.zzz
    REG_DATUM = '[\d]{4,4}[\D\W][\d]{1,2}[\D\W][\d]{1,2}|[\d]{4,4}[0-1][\d][0-3][\d]|[\d]{1,2}[\D\W][\d]{1,2}[\D\W][\d]{2,4}',
        /* Vorsicht nicht Narrensicher! Kann nur der groben Prüfung dienen
            1999-2.31 ISO (Trenner kann alles ausser Buchtabe/Ziffer sein)
            19991231  ISO
            31.12/19 German/Euro/US (Sehr locker)
        */

        // Rechte-Zuweisung
    RE_VIEW   = 0, // sieht alle allgemein zugängl. Daten
    RE_IVIEW  = 1, // sieht auch interne Daten
    RE_EDIT   = 2, // kann allg. Daten editieren
    RE_IEDIT  = 3, // editieren interner Daten (Personaldaten etc)
    RE_SEDIT  = 4, // kann Presets bearbeiten
    RE_DELE   = 5, // Löschberechtigung
    RE_ARCHIV = 6, // Depotverwaltung
        /*
        .
        siehe auch configs/adm_user.php */
    RE_ADMIN  = 15,
    RE_SU     = 16,

    WERT_QUOT = 0.03; // Wertsteigerungsquotient zur Berechnung der Vers.Summe

    // Sektion für 'sektion'
    $datei = [
        'admin' => 'configs/admin.php',
        'N'     => 'inc/ev_name.php',
        'P'     => 'inc/ev_person.php', // Personenverzeichnis
        'F'     => "inc/ev_figd.php", // filmografische Daten
        'Y'     => 'inc/ev_item_planar.php', // Eventhandler Plangegenstände
        'Z'     => 'inc/ev_item_3dobj.php',
        'K'     => 'inc/ev_item_fkop.php',
        'news'  => 'inc/news.php',
        'impr'  => 'inc/impressum.php'];

    // Admin-Array
    $adm_site = [
        'self'   => 'adm_self.php',
        'string' => 'adm_strings.php',
        'orte'   => 'adm_orte.php',
        'lort'   => 'adm_lort.php',
        'user'   => 'adm_user.php',
        'fgd_imp' => 'film_import.php'];

    /** Erzeugt ein Anmeldeformular für Auth und wertet es aus
     *
     * @param string $username Der zuletzt übergebene Benutzername
     * @param bool $status     Der Authorisationszustand
     * @param object $auth     Das Auth-Objekt
     */
    function loginFunction($username = null, $status = null, &$auth = null) {
        echo <<<FORM
    <form action={$_SERVER['PHP_SELF']} method='post' accept-charset=utf-8
        style='position:absolute; top:150px; left:150px; padding:20px; text-align:center;
        border:1px solid #0080ff; border-radius: 1em; z-index:1000;'>
    <table><tr><td style="vertical-align:middle; padding-left:20px;">
    <input type='text' name='username' value='gast'
        style='width:120px; text-align:center; margin-bottom:5px;'
        onfocus="if (this.value=='gast'){this.value='';}" /><br />
    <input  type='password' name='password' value='gast'
        style='width:120px; text-align:center'
        onfocus="if (this.value=='gast'){this.value='';}" /><br />
    <input style='margin-top:10px; width:120px' type='submit' name='submit' value='einloggen' />
    </td><td>
        <img src="images/password.png" alt="Password" style="padding-left:20px" />
    </td></tr></table></form>
FORM;
    }
}